### PR TITLE
namespacing the CSS

### PR DESCRIPTION
**Pull request by Pomax**

### CODE REVIEW

**Comment by MichaelKohler** [comment]
there are some errors e.g. https://github.com/Pomax/webmaker-auth-client/commit/7ceeb4079bd4cea3486951c363e9f3fe399cb940#diff-377ead5366f37d151d16ff13634e46dbR219
actually that's true for every line (there is always the original first character missing)

**Comment by cadecairos** [comment]
As mkohler (irc) pointed out, there's some missing characters in the css rules

**Comment by MichaelKohler** [comment]
looks good to me :)

**Comment by cadecairos** [comment]
Yes, This looks good!

**Comment by cadecairos** [comment]
merged!

https://github.com/mozilla/webmaker-auth-client/commit/4c42e42ade91a1cf16d7ecf3baced2d32955ba05

**Pull request closed without merging**
