### PR TITLE
Don't rely on bower for CommonJS requires.

### PR DESCRIPTION
**Pull request by brianloveswords**
We can't rely on paths to the `bower_components` directory being where
we think they are since each project can change where bower components
get installed (even for dependencies) with .bowerrc configuration.

Rather than rely on bower at all, I used the NPM versions of
`webmaker-analytics` and `cookie`. For EventEmitter, I changed the
method calls from the implementation-specific `emitEvent` to `emit`,
which is compatible with node and the browser implementation the AMD
version uses.

### CODE REVIEW

**Comment by brianloveswords** [comment]
@jbuck can this get merged?

**Comment by jbuck** [comment]
@brianloveswords Crap, sorry! Totally dropped the ball on merging this.

**Comment by brianloveswords** [comment]
np @jbuck! can you also publish it to NPM? I'd say a minor version bump vs patch.

**Comment by jbuck** [comment]
Published webmaker-auth-client@0.2.0

**Comment by brianloveswords** [comment]
Siiiiiiick :+1:

**Pull request merged**
